apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{name}}-{{serviceType}}-{{environment}}
  namespace: argocd

spec:
  destination:
    server: {{ .Values.spec.destination.server }} 
    namespace: {{name}}-{{serviceType}}-{{environment}}

  project: {{ .Values.spec.project }}

  source:
    path: charts/{{serviceType}}/{{name}}
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
