name: Update Readme

on:
  push:
    tags:
      - v*.*.*

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update Readme In Checked-Out Code
        run: |
          sed -E -i "s@(https://github.com/team-xquare/xctl/releases/download/).*(/xctl-).*(-(linux|windows|darwin)-(amd64|arm64)\.tar\.gz)@\1${{steps.get_version.outputs.VERSION}}\2${{steps.get_version.outputs.VERSION}}\3@g" ${GITHUB_WORKSPACE}/README.md
          sed -E -i "s@(/tmp/xctl-).*(-(linux|windows|darwin)-(amd64|arm64))@\1${{steps.get_version.outputs.VERSION}}\2@g" ${GITHUB_WORKSPACE}/README.md

      - name: Commit The New Version Reamde
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🚀 :: Deploy new version ${{ steps.get_version.outputs.VERSION }}"
          branch: master
          commit_options: "--no-verify --signoff"
          repository: .
          commit_user_name: XQUARE GitOps Bot
          commit_user_email: teamxquare@gmail.com
          commit_author: XQUARE GitOps Bot <teamxquare@gmail.com>
